;; Cooking task - making eggs

(define (problem cooking-eggs)
	(:domain cooking)
	
	(:objects 
		fridge cabinet shed table freezer - location
		eggs strawberry spatula scoop knife salt icecream - obj ;;squeegee cheese grater
		pan bowl plate0 blender glass - container ;;plate1 
		oil-can - spray
		obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 - cons-part
	)
	
	(:init
		(atLoc eggs fridge)
		(atLoc icecream freezer)
		;;(atLoc cheese fridge)
		(atLoc strawberry fridge)
		;;(atLoc pancake fridge)
		(atLoc salt table)
		;;(atLoc grater cabinet)
		(atLoc spatula cabinet)
		(atLoc knife cabinet)
		;;(atLoc squeegee shed)
		(empty pan)
		(empty bowl)
		(empty plate0)
		;;(empty plate1)
		(empty glass)
		(empty blender)
		(isSpatula spatula)
		(isIngredient salt)
		(isIngredient icecream)
		(isScoop scoop)
		;;(isGrater grater)
		(haveSpatula)
				
		;;(isSqueegee squeegee)
		(isMixable bowl)
		(isPourable eggs)
		(isPourable strawberry)
		;;(isPourable pancake)
		(isUtensil pan)
		(isBlender blender)
		(isKnife knife)
		(isSliceable strawberry)
		(isDirty strawberry)
		
		;; Differentiate parts
		
		(isDiff obj1 obj2)
		(isDiff obj1 obj3)
		(isDiff obj1 obj4)
		(isDiff obj1 obj5)
		(isDiff obj1 obj6)
		(isDiff obj1 obj7)
		(isDiff obj1 obj8)
		(isDiff obj1 obj9)
		(isDiff obj1 obj0)
		
		(isDiff obj2 obj1)
		(isDiff obj2 obj3)
		(isDiff obj2 obj4)
		(isDiff obj2 obj5)
		(isDiff obj2 obj6)
		(isDiff obj2 obj7)
		(isDiff obj2 obj8)
		(isDiff obj2 obj9)
		(isDiff obj2 obj0)
		
		(isDiff obj3 obj2)
		(isDiff obj3 obj1)
		(isDiff obj3 obj4)
		(isDiff obj3 obj5)
		(isDiff obj3 obj6)
		(isDiff obj3 obj7)
		(isDiff obj3 obj8)
		(isDiff obj3 obj9)
		(isDiff obj3 obj0)
		
		(isDiff obj4 obj2)
		(isDiff obj4 obj3)
		(isDiff obj4 obj1)
		(isDiff obj4 obj5)
		(isDiff obj4 obj6)
		(isDiff obj4 obj7)
		(isDiff obj4 obj8)
		(isDiff obj4 obj9)
		(isDiff obj4 obj0)
		
		(isDiff obj5 obj2)
		(isDiff obj5 obj3)
		(isDiff obj5 obj4)
		(isDiff obj5 obj1)
		(isDiff obj5 obj6)
		(isDiff obj5 obj7)
		(isDiff obj5 obj8)
		(isDiff obj5 obj9)
		(isDiff obj5 obj0)
		
		(isDiff obj6 obj2)
		(isDiff obj6 obj3)
		(isDiff obj6 obj4)
		(isDiff obj6 obj5)
		(isDiff obj6 obj1)
		(isDiff obj6 obj7)
		(isDiff obj6 obj8)
		(isDiff obj6 obj9)
		(isDiff obj6 obj0)
		
		(isDiff obj7 obj2)
		(isDiff obj7 obj3)
		(isDiff obj7 obj4)
		(isDiff obj7 obj5)
		(isDiff obj7 obj6)
		(isDiff obj7 obj1)
		(isDiff obj7 obj8)
		(isDiff obj7 obj9)
		(isDiff obj7 obj0)
		
		(isDiff obj8 obj2)
		(isDiff obj8 obj3)
		(isDiff obj8 obj4)
		(isDiff obj8 obj5)
		(isDiff obj8 obj6)
		(isDiff obj8 obj7)
		(isDiff obj8 obj1)
		(isDiff obj8 obj9)
		(isDiff obj8 obj0)
		
		(isDiff obj9 obj2)
		(isDiff obj9 obj3)
		(isDiff obj9 obj4)
		(isDiff obj9 obj5)
		(isDiff obj9 obj6)
		(isDiff obj9 obj7)
		(isDiff obj9 obj8)
		(isDiff obj9 obj1)
		(isDiff obj9 obj0)
		
		(isDiff obj0 obj2)
		(isDiff obj0 obj3)
		(isDiff obj0 obj4)
		(isDiff obj0 obj5)
		(isDiff obj0 obj6)
		(isDiff obj0 obj7)
		(isDiff obj0 obj8)
		(isDiff obj0 obj9)
		(isDiff obj0 obj1)

	)
	
	(:goal 
		(and 
		(isFullCooked eggs)
		;;(isFullCooked pancake)
		(in eggs plate0)
		(in salt eggs)
		;;(in pancake plate1)
		(isSmoothie strawberry)
		(on icecream strawberry)
		;;(on cheese eggs)
		(in strawberry glass)
		)
	)
)	
	
	