;; Cleaning task

(define (problem cleaning-house)
	(:domain cleaning)
	
	(:objects
		shed bedroom drying-rack table cabinet fridge cupboard - location
		bookshelf - shelf
		garbage-bin - trash
		rake squeegee clothes leaves duster wipes hammer iron - obj
		mantlepiece - smallObj
		window floor counter dining-table - surface
		obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 - cons-part
	)
	
	(:init
		(atLoc duster cabinet)
		(atLoc clothes bedroom)
		;;(atLoc empty-carton fridge)
		(atLoc mantlepiece table)
		(atLoc wipes cabinet)
		(atLoc iron cupboard)
		
		(isRake rake)
		(isDuster duster)
		(isSqueegee squeegee)
		(isRack drying-rack)
		(isDisinfectant wipes)
		(isIron iron)
		(isHammer hammer)
		
		(isRakeable leaves)
		(isDirty clothes)
		(isDirty window)
		(isDirty counter)
		(isDirty mantlepiece)
		(isDirty floor)
		(isMessy dining-table)
		;;(isTrash empty-carton)
		
		(haveRake)
		
		(isDiff obj1 obj2)
		(isDiff obj1 obj3)
		(isDiff obj1 obj4)
		(isDiff obj1 obj5)
		(isDiff obj1 obj6)
		(isDiff obj1 obj7)
		(isDiff obj1 obj8)
		(isDiff obj1 obj9)
		(isDiff obj1 obj0)
		
		(isDiff obj2 obj1)
		(isDiff obj2 obj3)
		(isDiff obj2 obj4)
		(isDiff obj2 obj5)
		(isDiff obj2 obj6)
		(isDiff obj2 obj7)
		(isDiff obj2 obj8)
		(isDiff obj2 obj9)
		(isDiff obj2 obj0)
		
		(isDiff obj3 obj2)
		(isDiff obj3 obj1)
		(isDiff obj3 obj4)
		(isDiff obj3 obj5)
		(isDiff obj3 obj6)
		(isDiff obj3 obj7)
		(isDiff obj3 obj8)
		(isDiff obj3 obj9)
		(isDiff obj3 obj0)
		
		(isDiff obj4 obj2)
		(isDiff obj4 obj3)
		(isDiff obj4 obj1)
		(isDiff obj4 obj5)
		(isDiff obj4 obj6)
		(isDiff obj4 obj7)
		(isDiff obj4 obj8)
		(isDiff obj4 obj9)
		(isDiff obj4 obj0)
		
		(isDiff obj5 obj2)
		(isDiff obj5 obj3)
		(isDiff obj5 obj4)
		(isDiff obj5 obj1)
		(isDiff obj5 obj6)
		(isDiff obj5 obj7)
		(isDiff obj5 obj8)
		(isDiff obj5 obj9)
		(isDiff obj5 obj0)
	
		(isDiff obj6 obj2)
		(isDiff obj6 obj3)
		(isDiff obj6 obj4)
		(isDiff obj6 obj5)
		(isDiff obj6 obj1)
		(isDiff obj6 obj7)
		(isDiff obj6 obj8)
		(isDiff obj6 obj9)
		(isDiff obj6 obj0)
		
		(isDiff obj7 obj2)
		(isDiff obj7 obj3)
		(isDiff obj7 obj4)
		(isDiff obj7 obj5)
		(isDiff obj7 obj6)
		(isDiff obj7 obj1)
		(isDiff obj7 obj8)
		(isDiff obj7 obj9)
		(isDiff obj7 obj0)
		
		(isDiff obj8 obj2)
		(isDiff obj8 obj3)
		(isDiff obj8 obj4)
		(isDiff obj8 obj5)
		(isDiff obj8 obj6)
		(isDiff obj8 obj7)
		(isDiff obj8 obj1)
		(isDiff obj8 obj9)
		(isDiff obj8 obj0)
		
		(isDiff obj9 obj2)
		(isDiff obj9 obj3)
		(isDiff obj9 obj4)
		(isDiff obj9 obj5)
		(isDiff obj9 obj6)
		(isDiff obj9 obj7)
		(isDiff obj9 obj8)
		(isDiff obj9 obj1)
		(isDiff obj9 obj0)
		
		(isDiff obj0 obj2)
		(isDiff obj0 obj3)
		(isDiff obj0 obj4)
		(isDiff obj0 obj5)
		(isDiff obj0 obj6)
		(isDiff obj0 obj7)
		(isDiff obj0 obj8)
		(isDiff obj0 obj9)
		(isDiff obj0 obj1)
	)
	
	(:goal
		(and
		(isRaked leaves)
		(isClean clothes)
		(isClean window)
		(isFolded clothes)
		;;(atLoc empty-carton garbage-bin)
		(isStowed mantlepiece)
		(isVacuumed floor)
		(isDisinfected counter)
		(atLoc wipes garbage-bin)
		(isCleared dining-table)
		)
	)
)

